/**
 * Traducción heurística de texto mecánico D&D (inglés → español) para contenido PHB
 * sin fuente Foundry. Usado en scripts de build, no en runtime de reglas.
 */
import { limpiarTextoFoundry } from "./foundry-text-clean";

/** Evita sustituir "you" dentro de palabras como "toward". */
const WB = String.raw`(?<![A-Za-záéíóúñ])`;
const WE = String.raw`(?![A-Za-záéíóúñ])`;

const PHRASES: [RegExp, string][] = [
  [/You gain the following benefits\.?/gi, "Obtienes los siguientes beneficios."],
  [/When you /gi, "Cuando tú "],
  [/Whenever you /gi, "Siempre que tú "],
  [/While you /gi, "Mientras tú "],
  [/If you /gi, "Si tú "],
  [/Until you /gi, "Hasta que tú "],
  [/As an action,? /gi, "Como acción, "],
  [/As a bonus action,? /gi, "Como acción adicional, "],
  [/As a reaction,? /gi, "Como reacción, "],
  [/On a hit,? /gi, "Si impactas, "],
  [/On a failed save,? /gi, "Si falla la salvación, "],
  [/On a successful save,? /gi, "Si tiene éxito en la salvación, "],
  [/Make a /gi, "Haz una "],
  [/choose one /gi, "elige una "],
  [/Choose one /gi, "Elige una "],
  [/one creature /gi, "una criatura "],
  [/One creature /gi, "Una criatura "],
  [/within range /gi, "dentro del alcance "],
  [/spellcasting ability /gi, "característica de lanzamiento de conjuros "],
  [/proficiency bonus/gi, "bonificador de competencia"],
  [/Proficiency Bonus/gi, "Bonificador de competencia"],
  [/Tool Proficiency/gi, "Competencia con herramientas"],
  [/Skill Proficiencies/gi, "Competencias en pericias"],
  [/nonmagical item/gi, "objeto no mágico"],
  [/percent discount/gi, "por ciento de descuento"],
  [/Fast Crafting/gi, "Fabricación rápida"],
  [/Bonus Action\b/gi, "acción adicional"],
  [/\bbonus action\b/gi, "acción adicional"],
  [/\bMagic Action\b/gi, "acción mágica"],
  [/\bUtilize action\b/gi, "acción Utilizar"],
  [/\bDash action\b/gi, "acción de Correr"],
  [/\bDisengage action\b/gi, "acción de Retirada"],
  [/\bAction\b/g, "acción"],
  [/\baction\b/g, "acción"],
  [/\bReaction\b/g, "reacción"],
  [/\breaction\b/g, "reacción"],
  [/\bAdvantage\b/gi, "ventaja"],
  [/\badvantage\b/gi, "ventaja"],
  [/\bDisadvantage\b/gi, "desventaja"],
  [/\bdisadvantage\b/gi, "desventaja"],
  [/\bDarkvision\b/gi, "visión en la oscuridad"],
  [/\bRitual\b/gi, "ritual"],
  [/\bRage\b/gi, "Rabia"],
  [/\bFly Speed\b/gi, "velocidad de vuelo"],
  [/\bClimb Speed\b/gi, "velocidad de escalada"],
  [/\bSwim Speed\b/gi, "velocidad de natación"],
  [/\bSpeed\b/gi, "velocidad"],
  [/\bLarge\b/g, "Grande"],
  [/\bSmall\b/g, "Pequeño"],
  [/\bMedium\b/g, "Mediano"],
  [new RegExp(`${WB}You${WE}`, "g"), "Tú"],
  [new RegExp(`${WB}you${WE}`, "g"), "tú"],
  [new RegExp(`${WB}Your${WE}`, "g"), "Tu"],
  [new RegExp(`${WB}your${WE}`, "g"), "tu"],
  [/\bLong Rest\b/gi, "descanso largo"],
  [/\bShort Rest\b/gi, "descanso corto"],
  [/\bHit Points?\b/gi, "puntos de golpe"],
  [/\bhit points?\b/gi, "puntos de golpe"],
  [/\bHit Point\b/gi, "punto de golpe"],
  [/\bSaving Throw\b/gi, "tirada de salvación"],
  [/\bsaving throw\b/gi, "tirada de salvación"],
  [/\bSpell Attack\b/gi, "ataque de conjuro"],
  [/\bspell attack\b/gi, "ataque de conjuro"],
  [/\bRanged Spell Attack\b/gi, "ataque de conjuro a distancia"],
  [/\bMelee Spell Attack\b/gi, "ataque de conjuro cuerpo a cuerpo"],
  [/\bAbility Check\b/gi, "prueba de característica"],
  [/\battack roll\b/gi, "tirada de ataque"],
  [/\bAttack Roll\b/gi, "tirada de ataque"],
  [/\bCantrip Upgrade\b/gi, "Mejora de truco"],
  [/\bUsing a Higher-Level Spell Slot\b/gi, "Usando un espacio de conjuro de nivel superior"],
  [/\bAt Higher Levels\b/gi, "A niveles superiores"],
  [/\bCreatures\b/gi, "criaturas"],
  [/\bCreature\b/gi, "criatura"],
  [/\bRange\b/g, "Alcance"],
  [/\brange\b/g, "alcance"],
  [/\bDuration\b/g, "Duración"],
  [/\bduration\b/g, "duración"],
  [/\bInstantaneous\b/gi, "Instantáneo"],
  [/\bConcentration\b/gi, "Concentración"],
  [/\bfeet\b/gi, "pies"],
  [/\bfoot\b/gi, "pie"],
  [/\bminutes\b/gi, "minutos"],
  [/\bminute\b/gi, "minuto"],
  [/\bhours\b/gi, "horas"],
  [/\bhour\b/gi, "hora"],
  [/\brounds\b/gi, "asaltos"],
  [/\bround\b/gi, "asalto"],
  [/\bdays\b/gi, "días"],
  [/\bday\b/gi, "día"],
  [/\bcast the /gi, "lanzas el conjuro "],
  [/\bcan cast /gi, "puedes lanzar "],
  [/\bspell but only as a /gi, "conjuro, pero solo como "],
  [/\bspells but only as /gi, "conjuros, pero solo como "],
  [/\bmelee attack/gi, "ataque cuerpo a cuerpo"],
  [/\branged attack/gi, "ataque a distancia"],
  [/\bweapon attack/gi, "ataque con arma"],
  [/\btakes /gi, "recibe "],
  [/\btake /gi, "recibe "],
  [/\bdamage/gi, "daño"],
  [/\bDamage/gi, "Daño"],
  [/\btarget/gi, "objetivo"],
  [/\bTarget/gi, "Objetivo"],
  [/\ballies/gi, "aliados"],
  [/\benemies/gi, "enemigos"],
  [/\benemy/gi, "enemigo"],
  [/\bcondition/gi, "condición"],
  [/\bresistance/gi, "resistencia"],
  [/\bResistance/gi, "Resistencia"],
  [/\bimmune/gi, "inmune"],
  [/\bactivate your /gi, "activas tu "],
  [/\bfinish a /gi, "terminas un "],
  [/\bfinish another /gi, "terminas otro "],
  [/\bwearing any armor/gi, "llevas armadura"],
  [/\baren't wearing/gi, "no llevas"],
  [/\bhit it with/gi, "la impactas con"],
  [/\bhit by/gi, "impactado por"],
  [/\bof your choice/gi, "de tu elección"],
  [/\bfollowing options/gi, "siguientes opciones"],
  [/\bgain one of the following/gi, "ganas una de las siguientes"],
  [/\bthe following benefits/gi, "los siguientes beneficios"],
  [/\bstarting when you /gi, "a partir de cuando tú "],
  [/\bbeginning at /gi, "a partir del nivel "],
  [/\blevel of /gi, "nivel de "],
  [/\bcharacter level/gi, "nivel de personaje"],
  [/\bspell slot/gi, "espacio de conjuro"],
  [/\bspell slots/gi, "espacios de conjuro"],
  [/\bhigher.level spell slot/gi, "espacio de conjuro de nivel superior"],
  [/\bverbal,? somatic/gi, "verbal, somático"],
  [/\bVerbal,? Somatic/gi, "Verbal, somático"],
  [/\bMaterial component/gi, "Componente material"],
  [/\bconcentration,? up to /gi, "concentración, hasta "],
  [/\bup to /gi, "hasta "],
  [/\bself/gi, "personal"],
  [/\bSelf/gi, "Personal"],
  [/\btouch/gi, "toque"],
  [/\bTouch/gi, "Toque"],
  [/\bsight/gi, "vista"],
  [/\bhearing/gi, "oído"],
  [/\btelepathy/gi, "telepatía"],
];

const DAMAGE_ES: Record<string, string> = {
  acid: "ácido",
  bludgeoning: "contundente",
  cold: "frío",
  fire: "fuego",
  force: "fuerza",
  lightning: "relámpago",
  necrotic: "necrótico",
  piercing: "perforante",
  poison: "veneno",
  psychic: "psíquico",
  radiant: "radiante",
  slashing: "cortante",
  thunder: "trueno",
};

const ABILITY_ES: Record<string, string> = {
  strength: "Fuerza",
  dexterity: "Destreza",
  constitution: "Constitución",
  intelligence: "Inteligencia",
  wisdom: "Sabiduría",
  charisma: "Carisma",
};

const CONDITION_ES: Record<string, string> = {
  blinded: "cegado",
  charmed: "hechizado",
  deafened: "ensordecido",
  frightened: "asustado",
  grappled: "agarrado",
  incapacitated: "incapacitado",
  invisible: "invisible",
  paralyzed: "paralizado",
  petrified: "petrificado",
  poisoned: "envenenado",
  prone: "derribado",
  restrained: "apresado",
  stunned: "aturdido",
  unconscious: "inconsciente",
};

/** Nombres oficiales en español para conjuros PHB fuera del SRD 2024. */
export const PHB_SPELL_NAMES_ES: Record<string, string> = {
  "arcane-gate": "Puerta arcana",
  "armor-of-agathys": "Armadura de Agathys",
  "arms-of-hadar": "Brazos de Hadar",
  "aura-of-purity": "Aura de pureza",
  "aura-of-vitality": "Aura de vitalidad",
  "banishing-smite": "Golpe desterrador",
  "beast-sense": "Sentido bestial",
  "bigbys-hand": "Mano de Bigby",
  "blade-ward": "Resguardo de hoja",
  "blinding-smite": "Golpe cegador",
  "circle-of-power": "Círculo de poder",
  "cloud-of-daggers": "Nube de dagas",
  "compelled-duel": "Duelo forzado",
  "conjure-barrage": "Conjurar andanada",
  "conjure-volley": "Conjurar salva",
  "cordon-of-arrows": "Cerca de flechas",
  "crown-of-madness": "Corona de locura",
  "crusaders-mantle": "Manto de cruzado",
  "destructive-wave": "Onda destructiva",
  "elemental-weapon": "Arma elemental",
  "feign-death": "Fingir muerte",
  "fount-of-moonlight": "Fuente de luz lunar",
  friends: "Amigos",
  "grasping-vine": "Enredadera atrapadora",
  "hail-of-thorns": "Lluvia de espinas",
  "hunger-of-hadar": "Hambre de Hadar",
  "jallarzis-storm-of-radiance": "Tormenta radiante de Jallarzi",
  "lightning-arrow": "Flecha de relámpago",
  "mind-sliver": "Astilla mental",
  "power-word-fortify": "Palabra de poder: fortificar",
  "staggering-smite": "Golpe tambaleante",
  "steel-wind-strike": "Golpe del viento de acero",
  "summon-aberration": "Invocar aberración",
  "summon-beast": "Invocar bestia",
  "summon-celestial": "Invocar celestial",
  "summon-construct": "Invocar constructo",
  "summon-elemental": "Invocar elemental",
  "summon-fey": "Invocar feérico",
  "summon-fiend": "Invocar infernal",
  "summon-undead": "Invocar no muerto",
  "swift-quiver": "Aljaba presta",
  "synaptic-static": "Estática sináptica",
  "tashas-bubbling-cauldron": "Caldero burbujeante de Tasha",
  telepathy: "Telepatía",
  "thorn-whip": "Latigazo de espinas",
  thunderclap: "Aplauso atronador",
  "thunderous-smite": "Golpe atronador",
  "toll-the-dead": "Doblegar a los muertos",
  "witch-bolt": "Rayo de bruja",
  "word-of-radiance": "Palabra de radiancia",
  "wrathful-smite": "Golpe iracundo",
  "yolandes-regal-presence": "Presencia regia de Yolande",
};

const VERB_ES: Record<string, string> = {
  create: "creas",
  makes: "hace",
  make: "haz",
  cast: "lanzas",
  casts: "lanza",
  gain: "ganas",
  gains: "gana",
  choose: "elige",
  chooses: "elige",
  deal: "infliges",
  deals: "inflige",
  throw: "lanzas",
  hurl: "arrojas",
  summon: "invocas",
  conjure: "conjuras",
  target: "objetivo",
  targets: "objetivos",
  against: "contra",
  within: "dentro de",
  through: "a través de",
  until: "hasta",
  while: "mientras",
  during: "durante",
  each: "cada",
  every: "cada",
  another: "otro",
  other: "otro",
  different: "distinto",
  same: "mismo",
  equal: "igual",
  half: "mitad",
  twice: "el doble",
  double: "doble",
  extra: "adicional",
  additional: "adicional",
  maximum: "máximo",
  minimum: "mínimo",
  number: "número",
  total: "total",
  roll: "tirada",
  rolls: "tiradas",
  failed: "fallida",
  successful: "exitosa",
  success: "éxito",
  failure: "fallo",
  fail: "falla",
  passes: "supera",
  pass: "supera",
  saving: "salvación",
  attack: "ataque",
  attacks: "ataques",
  weapon: "arma",
  weapons: "armas",
  armor: "armadura",
  shield: "escudo",
  wielding: "empuñas",
  wearing: "llevas",
  holding: "sostienes",
  carried: "transportado",
  worn: "llevado",
  visible: "visible",
  invisible: "invisible",
  magical: "mágico",
  nonmagical: "no mágico",
  object: "objeto",
  objects: "objetos",
  surface: "superficie",
  ground: "suelo",
  air: "aire",
  water: "agua",
  fire: "fuego",
  cold: "frío",
  lightning: "relámpago",
  thunder: "trueno",
  acid: "ácido",
  poison: "veneno",
  force: "fuerza",
  radiant: "radiante",
  necrotic: "necrótico",
  psychic: "psíquico",
  bludgeoning: "contundente",
  piercing: "perforante",
  slashing: "cortante",
};

export function traducirTextoDnD(text: string): string {
  let out = limpiarTextoFoundry(text);
  for (const [pattern, replacement] of PHRASES) {
    out = out.replace(pattern, replacement as string);
  }
  for (const [en, es] of Object.entries(DAMAGE_ES)) {
    out = out.replace(new RegExp(`\\b${en}\\b`, "gi"), es);
  }
  for (const [en, es] of Object.entries(ABILITY_ES)) {
    out = out.replace(new RegExp(`\\b${en}\\b`, "g"), es);
  }
  for (const [en, es] of Object.entries(CONDITION_ES)) {
    out = out.replace(new RegExp(`\\b${en}\\b`, "gi"), es);
  }
  for (const [en, es] of Object.entries(VERB_ES)) {
    out = out.replace(new RegExp(`\\b${en}\\b`, "gi"), es);
  }
  return out.replace(/\s+/g, " ").trim();
}
